version: '3.8'

services:
  new-app-dev:
    container_name: expressnext-crm-dev-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3001:3001"
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development