version: '3.8'

services:
  new-app:
    container_name: expressnext-crm-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: always
    ports:
      - "3001:3001"
    # Make sure you have a .env file locally for this to work
    env_file:
      - .env