name: Build and Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/expressnext-crm:latest
        build-args: |
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy to EC2 via SSM
      run: |
        # Create deployment script
        cat > deploy-script.sh << 'EOF'
        #!/bin/bash
        set -e
        
        echo "Starting deployment..."
        
        # Pull latest image
        docker pull ${{ secrets.DOCKER_USERNAME }}/expressnext-crm:latest
        
        # Stop and remove existing container (if running)
        docker stop expressnext-crm || true
        docker rm expressnext-crm || true
        
        # Run new container
        docker run -d \
          --name expressnext-crm \
          -p 3001:3001 \
          --env-file /home/${{ secrets.EC2_USER }}/.env \
          --restart unless-stopped \
          ${{ secrets.DOCKER_USERNAME }}/expressnext-crm:latest
        
        # Clean up old images
        docker image prune -f
        
        echo "Deployment completed successfully!"
        EOF
        
        # Send and execute script via SSM
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["$(cat deploy-script.sh)"]' \
          --timeout-seconds 300 \
          --region ${{ secrets.AWS_REGION }} \
          --output text \
          --query 'Command.CommandId' > command-id.txt
        
        # Wait for command to complete and get output
        COMMAND_ID=$(cat command-id.txt)
        echo "SSM Command ID: $COMMAND_ID"
        
        # Wait for completion
        aws ssm wait command-executed \
          --command-id $COMMAND_ID \
          --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
          --region ${{ secrets.AWS_REGION }}
        
        # Get command output
        aws ssm get-command-invocation \
          --command-id $COMMAND_ID \
          --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
          --region ${{ secrets.AWS_REGION }} \
          --query 'StandardOutputContent' \
          --output text
        
        # Check if command succeeded
        STATUS=$(aws ssm get-command-invocation \
          --command-id $COMMAND_ID \
          --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
          --region ${{ secrets.AWS_REGION }} \
          --query 'Status' \
          --output text)
        
        if [ "$STATUS" != "Success" ]; then
          echo "Deployment failed with status: $STATUS"
          # Get error output
          aws ssm get-command-invocation \
            --command-id $COMMAND_ID \
            --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
            --region ${{ secrets.AWS_REGION }} \
            --query 'StandardErrorContent' \
            --output text
          exit 1
        fi
        
        echo "Deployment completed successfully!"